name: Deploy via FTPS
on:
  push:
    branches: [main]

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Récupération du code source
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Étape de build (si nécessaire)
      - name: Build (si nécessaire)
        run: |
          # Ajoutez vos commandes de build ici si besoin
          echo "Aucune étape de build configurée"

      # 3️⃣ Synchronisation des fichiers via FTPS
      - name: Sync files via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_HST }}          
          username: ${{ secrets.FTP_USER }}    
          password: ${{ secrets.FTP_PASS }}    
          protocol: ftps                           
          port: 21                                 
          local-dir: ./app/                       
          server-dir: /sites/ent-facile.fr/
          exclude: |
            **/.git*
            **/node_modules/*
          dry-run: false
          verbose: true
